INSERT INTO OURVLE_CLONE.Courses (CourseID, CourseName, LecturerID)
SELECT 
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS CourseID,
    CONCAT('Course ', ROW_NUMBER() OVER (ORDER BY (SELECT NULL))) AS CourseName,
    (SELECT UserID FROM OURVLE_CLONE.Users WHERE UserType = 'lecturer' ORDER BY RAND() LIMIT 1) AS LecturerID
FROM 
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) AS dummy1
CROSS JOIN 
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) AS dummy2
LIMIT 200;
