INSERT INTO OURVLE_CLONE.Users (UserID, Username, Password, UserType)
SELECT 
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) + 100000 AS UserID,
    CONCAT('lecturer', ROW_NUMBER() OVER (ORDER BY (SELECT NULL))) AS Username,
    CONCAT('password', ROW_NUMBER() OVER (ORDER BY (SELECT NULL))) AS Password,
    'lecturer' AS UserType
FROM 
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) AS dummy1
CROSS JOIN 
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5) AS dummy2
LIMIT 100;
